# Generated by Django 5.1.12 on 2025-09-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('command_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=16)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField()),
                ('metric', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('ts', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
    ]
